#!/bin/bash

setup_homebrew() {
  if [ "$(which brew)" != '/usr/local/bin/brew' ]; then
    ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  fi
}

brew_install() {
  for package in $@; do
    if [ -n "$(brew info $package | grep 'Not installed')" ]; then
      brew install $package
    fi
  done
}

rvm_install() {
  local ruby_version=2.1.1

  if [ ! -f ~/.rvm/bin/rvm ]; then
    \curl -sSL https://get.rvm.io | bash -s -- --ignore-dotfiles
  fi

  if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
      # First try to load from a user install
      source "$HOME/.rvm/scripts/rvm"
  fi

  if [ -z "$(rvm list rubies | grep $ruby_version)" ]; then
    rvm install ruby-$ruby_version
  fi
  rvm use ruby-$ruby_version
}

setup_homebrew
brew_install git
rvm_install

(cd ~/code; [ ! -d gops ] && git clone git@github.com:goodsearch/gops.git; cd gops; git pull)
cd ~/code/sprout-wrap

if [ -z "$(gem list bundler)" ]; then
  gem install bundler --no-ri --no-rdoc
fi

unset RUBYOPT # [pk] this flag trips up rubygems native installs; unset it
bundle
bundle exec soloist
